In [6]:
import pandas as pd

data=pd.read_csv("운동처방결과데이터.csv")
data

,name,site_link,운동대상,체력항목,운동형태,운동부위,시설 필요유무
0,웨이트 트레이닝 루틴프로그램,/entry.naver?docId=3535306&categoryId=58501&ci...,청소년,근력/근지구력,웨이트기계,전신/가슴/상체/하체,Y
1,맨몸운동 루틴프로그램,/entry.naver?docId=3535307&categoryId=58501&ci...,청소년,근력/근지구력,맨몸,전신/가슴/상체/하체,N
2,앉았다 일어서며 팔 들어올리기,/entry.naver?docId=3535308&categoryId=58501&ci...,청소년,근력/근지구력,밴드,어깨측면/허벅지앞쪽,Y
3,런지하며 상체 비틀기,/entry.naver?docId=3535309&categoryId=58501&ci...,청소년,근력/근지구력,밴드,어깨측면/허벅지앞쪽,Y
4,팔 들어 올리며 런지,/entry.naver?docId=3535310&categoryId=58501&ci...,청소년,근력/근지구력,밴드,어깨뒤쪽/어깨측면/허벅지앞쪽,Y
...,...,...,...,...,...,...,...
521,탄력밴드 걸고 서기 평형성 운동 루틴 프로그램,/entry.naver?docId=3535842&categoryId=58501&ci...,NaN,NaN,NaN,NaN,NaN
522,베개 밟고 서기 평형성 운동 루틴 프로그램,/entry.naver?docId=3535843&categoryId=58501&ci...,NaN,NaN,NaN,NaN,NaN
523,의자잡고 서기 평형성운동 루틴 프로그램,/entry.naver?docId=3535844&categoryId=58501&ci...,NaN,NaN,NaN,NaN,NaN
524,사다리 이용 협응성운동 루틴 프로그램,/entry.naver?docId=3535845&categoryId=58501&ci...,NaN,NaN,NaN,NaN,NaN
525,우울증을 위한 협응성 운동,/entry.naver?docId=3535847&categoryId=58501&ci...,NaN,NaN,NaN,NaN,NaN

In [11]:
data2=data.iloc[0:496]
data2

,name,site_link,운동대상,체력항목,운동형태,운동부위,시설 필요유무
0,웨이트 트레이닝 루틴프로그램,/entry.naver?docId=3535306&categoryId=58501&ci...,청소년,근력/근지구력,웨이트기계,전신/가슴/상체/하체,Y
1,맨몸운동 루틴프로그램,/entry.naver?docId=3535307&categoryId=58501&ci...,청소년,근력/근지구력,맨몸,전신/가슴/상체/하체,N
2,앉았다 일어서며 팔 들어올리기,/entry.naver?docId=3535308&categoryId=58501&ci...,청소년,근력/근지구력,밴드,어깨측면/허벅지앞쪽,Y
3,런지하며 상체 비틀기,/entry.naver?docId=3535309&categoryId=58501&ci...,청소년,근력/근지구력,밴드,어깨측면/허벅지앞쪽,Y
4,팔 들어 올리며 런지,/entry.naver?docId=3535310&categoryId=58501&ci...,청소년,근력/근지구력,밴드,어깨뒤쪽/어깨측면/허벅지앞쪽,Y
...,...,...,...,...,...,...,...
491,풍선 튕기기,/entry.naver?docId=3535807&categoryId=58501&ci...,어르신,협응력,풍선,전신,Y
492,머리 위로 공 넘기기,/entry.naver?docId=3535808&categoryId=58501&ci...,어르신,협응력,공,전신,Y
493,발바닥 치기,/entry.naver?docId=3535809&categoryId=58501&ci...,어르신,협응력,맨몸,전신,N
494,앞뒤로 선넘기,/entry.naver?docId=3535810&categoryId=58501&ci...,어르신,협응력,맨몸,전신,N
495,좌우로 선넘기,/entry.naver?docId=3535811&categoryId=58501&ci...,어르신,협응력,맨몸,전신,N

In [13]:
data2.to_csv("운동처방데이터저장.csv", index=False)

In [37]:
address=input("주소를 입력하세요: ")
address.strip()
# 서울특별시 중구 필동로 1길30
# 서울특별시 중구 필동로1길 30(필동3가)

주소를 입력하세요: 서울특별시 중구 필동로1길 30(필동3가)

'서울특별시 중구 필동로1길 30(필동3가)'

In [44]:
import numpy as np
import pandas as pd
from urllib.request import urlopen
from urllib import parse
from urllib.request import Request
from urllib.error import HTTPError
from bs4 import BeautifulSoup
import json
import urllib

In [48]:
#naver map api key
client_id = '7mfj21mpta';    # 본인이 할당받은 ID 입력
client_pw = 'pdtBr9oxlKR3PS6WViF1vDykk4uSSFStHJt2xS0v';    # 본인이 할당받은 Secret 입력

api_url = 'https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query='

# 주소 목록 파일 (.csv)
# data = pd.read_csv('파일명.csv')
# 주소 목록 파일 (.xlsx)
# data = pd.read_excel('파일명.xlsx')

# 네이버 지도 API 이용해서 위경도 찾기
print(address)
add_urlenc = parse.quote(address)  
url = api_url + add_urlenc
request = Request(url)
request.add_header('X-NCP-APIGW-API-KEY-ID', client_id)
request.add_header('X-NCP-APIGW-API-KEY', client_pw)

try:
    response = urlopen(request)
except HTTPError as e:
    print('HTTP Error!')
    latitude = None
    longitude = None
else:
    rescode = response.getcode()
    if rescode == 200:
        response_body = response.read().decode('utf-8')
        response_body = json.loads(response_body)   # json
        if response_body['addresses'] == [] :
            print("'result' not exist!")
            latitude = None
            longitude = None
        else:
            latitude = response_body['addresses'][0]['y']
            longitude = response_body['addresses'][0]['x']
            print("위도: ", latitude, "경도: ", longitude)
            print("Success!")
    else:
        print('Response error code : %d' % rescode)
        latitude = None
        longitude = None

서울특별시 중구 필동로1길 30(필동3가)
위도:  37.5582582 경도:  127.0001869
Success!

In [60]:
list_add=list(address.split())
print(list_add[0], list_add[1])
si=list_add[0]
gu=list_add[1]

서울특별시 중구

In [51]:
data2=pd.read_csv("전국체육시설현황데이터.csv")
data2

,FACI_NM,FACI_GB_CD,FACI_GB_NM,FCOB_CD,FCOB_NM,FTYPE_CD,FTYPE_NM,FACI_STAT,FACI_ROAD_POST,FACI_ROAD_ADDR1,...,CP_YMD,TH_YMD,SDWN_YMD,NATION_YN,SSM_DSN_YN,ATNM_CHK_YN,DATA_FROM_GB_CD,DEL_YN,REG_DT,UPD_DT
0,(외립석입구),P,공공,P08,간이운동장,P0801,간이운동장,정상운영,NaN,NaN,...,,,,N,,N,NaN,N,2020-02-10,2020-02-10
1,(주)한샘레포츠타운(공단점),N,신고,N10,체력단련장업,N1001,체력단련장,정상운영,15433.0,경기도 안산시 단원구 동산로 63 (원시동),...,,,,N,,Y,NaN,N,2016-12-31,2017-02-26
2,(자산경로당),P,공공,P08,간이운동장,P0801,간이운동장,정상운영,39588.0,경상북도 김천시 자산3길 16 (성내동),...,,,,N,,N,SFMS,N,2020-02-10,2021-04-29
3,볼&큐 빌리어드클럽,N,신고,N11,당구장업,N1101,당구장,정상운영,426811.0,"경기도 안산시 상록구 반석로 88, 4층 (본오동)",...,,,,N,,Y,태블릿,N,2016-12-31,2019-01-14
4,안산 힘찬 태권도,N,신고,N08,체육도장업,N0805,태권도,정상운영,15535.0,경기도 안산시 상록구 각골로 127 (본오동),...,,,,N,,Y,SFMS,N,2016-12-31,2019-03-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108282,美 Diet Boxing Club,N,신고,N08,체육도장업,N0801,권투,정상운영,7262.0,서울특별시 영등포구 영등포로 85-1 (양평동1가),...,,,,N,,Y,태블릿,N,2016-12-30,2019-01-03
108283,우리 아이풀(舊 크레피아수영장),N,신고,N07,수영장업,N0701,실내,정상운영,302800.0,대전광역시 서구 계백로 1186 (가수원동),...,,,,N,N,N,NaN,N,2016-12-31,2018-09-19
108284,身휘트니스,N,신고,N10,체력단련장업,N1001,체력단련장,정상운영,463827.0,"경기도 성남시 분당구 성남대로 912, 지하1층 (야탑동, 분당BYC빌딩)",...,,,,N,,Y,태블릿,N,2016-12-31,2020-07-27
108285,태권道장 휘영찬,N,신고,N08,체육도장업,N0805,태권도,정상운영,302812.0,"대전광역시 서구 관저동로 66 (관저동, 3층)",...,,,,N,,Y,NaN,N,2016-12-31,2018-09-20
108286,道心성인태권도,N,신고,N08,체육도장업,N0805,태권도,정상운영,1384.0,서울특별시 도봉구 방학로 175(방학동),...,,,,N,,Y,SFMS,N,2021-09-01,2021-09-01

In [64]:
data3=data2[['FACI_STAT', 'CP_NM', 'CPB_NM', 'FACI_POINT_X', 'FACI_POINT_Y', 'FACI_TEL']]
data3

       FACI_STAT  CP_NM CPB_NM  FACI_POINT_X  FACI_POINT_Y      FACI_TEL
0           정상운영   경상북도    김천시           NaN           NaN           NaN
1           정상운영    경기도    안산시    126.797270     37.314431  031-492-3392
2           정상운영   경상북도    김천시    128.122092     36.120771  054-421-2318
3           정상운영    경기도    안산시    126.869468     37.296411  031-415-9970
4           정상운영    경기도    안산시    126.872700     37.300895           NaN
...          ...    ...    ...           ...           ...           ...
108282      정상운영  서울특별시   영등포구    126.891175     37.522315  02-2637-7712
108283      정상운영  대전광역시     서구    127.355226     36.304872  042-541-7944
108284      정상운영    경기도    성남시    127.129262     37.410966  031-783-8844
108285      정상운영  대전광역시     서구    127.340994     36.298068           NaN
108286      정상운영  서울특별시    도봉구    127.032648     37.662070           NaN

[108287 rows x 6 columns]

In [65]:
condition=(data3.FACI_STAT == '정상운영')
data4=data3[condition]
data4

       FACI_STAT  CP_NM CPB_NM  FACI_POINT_X  FACI_POINT_Y      FACI_TEL
0           정상운영   경상북도    김천시           NaN           NaN           NaN
1           정상운영    경기도    안산시    126.797270     37.314431  031-492-3392
2           정상운영   경상북도    김천시    128.122092     36.120771  054-421-2318
3           정상운영    경기도    안산시    126.869468     37.296411  031-415-9970
4           정상운영    경기도    안산시    126.872700     37.300895           NaN
...          ...    ...    ...           ...           ...           ...
108282      정상운영  서울특별시   영등포구    126.891175     37.522315  02-2637-7712
108283      정상운영  대전광역시     서구    127.355226     36.304872  042-541-7944
108284      정상운영    경기도    성남시    127.129262     37.410966  031-783-8844
108285      정상운영  대전광역시     서구    127.340994     36.298068           NaN
108286      정상운영  서울특별시    도봉구    127.032648     37.662070           NaN

[88134 rows x 6 columns]

In [66]:
data4.to_csv("정상운영체육시설.csv")

In [67]:
#si
same_si=data3['CP_NM']==si
target=data3[same_si]
target

       FACI_STAT  CP_NM CPB_NM  FACI_POINT_X  FACI_POINT_Y      FACI_TEL
252         정상운영  서울특별시   영등포구    126.891347     37.525494           NaN
253         정상운영  서울특별시    강동구    127.129657     37.556670   02-426-9729
261         정상운영  서울특별시    구로구    126.870255     37.504717  02-2688-0753
262         정상운영  서울특별시    송파구    127.125738     37.497661  02-2135-1788
265         정상운영  서울특별시    종로구    127.016000     37.574056           NaN
...          ...    ...    ...           ...           ...           ...
108269        폐업  서울특별시    관악구    126.913418     37.480527           NaN
108274      정상운영  서울특별시     중구    126.994825     37.561141           NaN
108278      정상운영  서울특별시   영등포구    126.897059     37.534560  02-2677-3067
108282      정상운영  서울특별시   영등포구    126.891175     37.522315  02-2637-7712
108286      정상운영  서울특별시    도봉구    127.032648     37.662070           NaN

[16433 rows x 6 columns]

In [77]:
#gu
same_gu=target['CPB_NM']==gu
target2=target[same_gu]
target2

# Y:위도, X:경도

       FACI_STAT  CP_NM CPB_NM  FACI_POINT_X  FACI_POINT_Y      FACI_TEL
298         정상운영  서울특별시     중구    126.991127     37.560088  02-2280-8000
326         정상운영  서울특별시     중구    127.016534     37.564217           NaN
327         정상운영  서울특별시     중구    126.973561     37.559473           NaN
414         정상운영  서울특별시     중구           NaN           NaN   02-730-9911
528         정상운영  서울특별시     중구    126.985168     37.562531           NaN
...          ...    ...    ...           ...           ...           ...
107696      정상운영  서울특별시     중구    127.020981     37.566794  02-2231-5547
107712      정상운영  서울특별시     중구    127.015401     37.558988  02-2238-8347
108212      정상운영  서울특별시     중구           NaN           NaN   02-779-4900
108213      정상운영  서울특별시     중구    126.986150     37.564903           NaN
108274      정상운영  서울특별시     중구    126.994825     37.561141           NaN

[432 rows x 6 columns]

In [100]:
target2.dtypes
# latitude.dtypes
# longitude.dtypes

FACI_STAT        object
CP_NM            object
CPB_NM           object
FACI_POINT_X    float64
FACI_POINT_Y    float64
FACI_TEL         object
dtype: object

In [131]:
target3=target2.dropna(subset=["FACI_POINT_X"])
target4=target3.dropna(subset=["FACI_POINT_Y"])

list1={0}
target4['거리']=pd.DataFrame(list1)
target4

       FACI_STAT  CP_NM CPB_NM  FACI_POINT_X  FACI_POINT_Y      FACI_TEL  거리
298         정상운영  서울특별시     중구    126.991127     37.560088  02-2280-8000 NaN
326         정상운영  서울특별시     중구    127.016534     37.564217           NaN NaN
327         정상운영  서울특별시     중구    126.973561     37.559473           NaN NaN
528         정상운영  서울특별시     중구    126.985168     37.562531           NaN NaN
529         정상운영  서울특별시     중구    126.985168     37.562531           NaN NaN
...          ...    ...    ...           ...           ...           ...  ..
107583      정상운영  서울특별시     중구    126.985128     37.560416           NaN NaN
107696      정상운영  서울특별시     중구    127.020981     37.566794  02-2231-5547 NaN
107712      정상운영  서울특별시     중구    127.015401     37.558988  02-2238-8347 NaN
108213      정상운영  서울특별시     중구    126.986150     37.564903           NaN NaN
108274      정상운영  서울특별시     중구    126.994825     37.561141           NaN NaN

[379 rows x 7 columns]

In [97]:
# import numbers
# import math

# class GeoUtil:
#     """
#     Geographical Utils
#     """
#     @staticmethod
#     def degree2radius(degree):
#         return degree * (math.pi/180)
    
#     @staticmethod
#     def get_harversion_distance(x1, y1, x2, y2, round_decimal_digits=5):
#         """
#         경위도 (x1,y1)과 (x2,y2) 점의 거리를 반환
#         Harversion Formula 이용하여 2개의 경위도간 거래를 구함(단위:Km)
#         """
#         if x1 is None or y1 is None or x2 is None or y2 is None:
#             return None
#         assert isinstance(x1, numbers.Number) and -180 <= x1 and x1 <= 180
#         assert isinstance(y1, numbers.Number) and  -90 <= y1 and y1 <=  90
#         assert isinstance(x2, numbers.Number) and -180 <= x2 and x2 <= 180
#         assert isinstance(y2, numbers.Number) and  -90 <= y2 and y2 <=  90

#         R = 6371 # 지구의 반경(단위: km)
#         dLon = GeoUtil.degree2radius(x2-x1)    
#         dLat = GeoUtil.degree2radius(y2-y1)

#         a = math.sin(dLat/2) * math.sin(dLat/2) \
#             + (math.cos(GeoUtil.degree2radius(y1)) \
#               *math.cos(GeoUtil.degree2radius(y2)) \
#               *math.sin(dLon/2) * math.sin(dLon/2))
#         b = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
#         return round(R * b, round_decimal_digits)

#     @staticmethod
#     def get_euclidean_distance(x1, y1, x2, y2, round_decimal_digits=5):        
#         """
#         유클리안 Formula 이용하여 (x1,y1)과 (x2,y2) 점의 거리를 반환
#         """
#         if x1 is None or y1 is None or x2 is None or y2 is None:
#             return None
#         assert isinstance(x1, numbers.Number) and -180 <= x1 and x1 <= 180
#         assert isinstance(y1, numbers.Number) and  -90 <= y1 and y1 <=  90
#         assert isinstance(x2, numbers.Number) and -180 <= x2 and x2 <= 180
#         assert isinstance(y2, numbers.Number) and  -90 <= y2 and y2 <=  90

#         dLon = abs(x2-x1) # 경도 차이
#         if dLon >= 180:   # 반대편으로 갈 수 있는 경우
#             dLon -= 360   # 반대편 각을 구한다
#         dLat = y2-y1      # 위도 차이
#         return round(math.sqrt(pow(dLon,2)+pow(dLat,2)),round_decimal_digits)

In [118]:
from scipy.spatial import distance
#round(distance.euclidean((경도,위도 ), (longitude, latitude)),5)
x_list=target4['FACI_POINT_X'].tolist()
y_list = target4['FACI_POINT_Y'].tolist()
list_dis=[]
#print(x_list,y_list)
for i in range(0,len(x_list)):
    val=round(distance.euclidean((float(longitude),float(latitude)), (x_list[i], y_list[i])),5)
    list_dis.append(val)
    
list_dis

[0.00924,
 0.0174,
 0.02665,
 0.01561,
 0.01561,
 0.03072,
 0.02297,
 0.01752,
 0.01752,
 0.01464,
 0.0229,
 0.01039,
 0.02584,
 0.00443,
 0.01265,
 0.01812,
 0.01906,
 0.02254,
 0.0229,
 0.01237,
 0.0134,
 0.01419,
 0.0105,
 0.00568,
 0.00785,
 0.02504,
 0.01434,
 0.00906,
 0.00557,
 0.0222,
 0.01561,
 0.02236,
 0.01399,
 0.01829,
 0.01248,
 0.00956,
 0.0222,
 0.01225,
 0.0119,
 0.02631,
 0.0229,
 0.03271,
 0.01951,
 0.01014,
 0.00814,
 0.01719,
 0.02172,
 0.00748,
 0.03572,
 0.03204,
 0.0168,
 0.02636,
 0.00994,
 0.01554,
 0.0191,
 0.00815,
 0.0099,
 0.01892,
 0.02353,
 0.02001,
 0.02114,
 0.00868,
 0.02226,
 0.01837,
 0.02266,
 0.01213,
 0.01056,
 0.01554,
 0.00996,
 0.02941,
 0.02941,
 0.01143,
 0.01143,
 0.03479,
 0.00542,
 0.0207,
 0.01369,
 0.01199,
 0.01303,
 0.00859,
 0.01344,
 0.01399,
 0.01297,
 0.01577,
 0.01124,
 0.02647,
 0.01906,
 0.01013,
 0.00324,
 0.0179,
 0.00492,
 0.01304,
 0.02257,
 0.00946,
 0.01094,
 0.01482,
 0.01238,
 0.00937,
 0.0168,
 0.01369,
 0.02235,
 0.01013,
 0.02559,
 0.01199,
 0.0112,
 0.01709,
 0.01014,
 0.02171,
 0.03209,
 0.00487,
 0.01708,
 0.00859,
 0.02109,
 0.02139,
 0.02637,
 0.01066,
 0.01274,
 0.00937,
 0.03142,
 0.02257,
 0.00352,
 0.01428,
 0.02,
 0.02109,
 0.02629,
 0.00373,
 0.033,
 0.02015,
 0.01214,
 0.02468,
 0.01836,
 0.01636,
 0.00909,
 0.02822,
 0.02551,
 0.01445,
 0.00487,
 0.01284,
 0.01886,
 0.01039,
 0.00525,
 0.00903,
 0.0314,
 0.01594,
 0.01211,
 0.01108,
 0.01091,
 0.02252,
 0.0247,
 0.0247,
 0.01214,
 0.00744,
 0.01392,
 0.03313,
 0.02164,
 0.02312,
 0.02051,
 0.02532,
 0.00346,
 0.01399,
 0.00819,
 0.02476,
 0.02417,
 0.02947,
 0.00743,
 0.00743,
 0.01826,
 0.01171,
 0.01388,
 0.00833,
 0.02527,
 0.02226,
 0.01748,
 0.00484,
 0.00731,
 0.00614,
 0.00614,
 0.00998,
 0.01543,
 0.01592,
 0.00894,
 0.01755,
 0.01772,
 0.0273,
 0.01777,
 0.02829,
 0.03488,
 0.0092,
 0.00921,
 0.03498,
 0.00998,
 0.01611,
 0.01583,
 0.0266,
 0.01196,
 0.01889,
 0.02378,
 0.01745,
 0.02864,
 0.02864,
 0.02215,
 0.0099,
 0.02881,
 0.01826,
 0.02065,
 0.01503,
 0.01502,
 0.01387,
 0.02896,
 0.01427,
 0.02208,
 0.00721,
 0.01083,
 0.01237,
 0.01199,
 0.03488,
 0.0095,
 0.0112,
 0.02247,
 0.02214,
 0.01639,
 0.01297,
 0.03224,
 0.019,
 0.00577,
 0.02347,
 0.02397,
 0.02552,
 0.0175,
 0.01054,
 0.02822,
 0.00972,
 0.01662,
 0.00528,
 0.01026,
 0.02833,
 0.01593,
 0.02416,
 0.02072,
 0.01045,
 0.00526,
 0.02747,
 0.01082,
 0.01428,
 0.01284,
 0.02397,
 0.00972,
 0.00799,
 0.01652,
 0.00503,
 0.0204,
 0.00474,
 0.01706,
 0.00911,
 0.0219,
 0.00906,
 0.02245,
 0.01208,
 0.01077,
 0.01612,
 0.01612,
 0.02628,
 0.02773,
 0.0182,
 0.01848,
 0.01348,
 0.02167,
 0.01982,
 0.00605,
 0.0247,
 0.02822,
 0.01457,
 0.01549,
 0.01293,
 0.01829,
 0.00492,
 0.02176,
 0.01746,
 0.01493,
 0.01214,
 0.00686,
 0.00621,
 0.00753,
 0.00503,
 0.03271,
 0.01523,
 0.02865,
 0.01557,
 0.02316,
 0.02705,
 0.0206,
 0.01115,
 0.01171,
 0.02417,
 0.0098,
 0.0098,
 0.01771,
 0.0213,
 0.01592,
 0.02464,
 0.01587,
 0.00206,
 0.01045,
 0.0105,
 0.01287,
 0.02045,
 0.02485,
 0.01344,
 0.00986,
 0.01333,
 0.01795,
 0.02244,
 0.0195,
 0.0165,
 0.00557,
 0.0165,
 0.03421,
 0.0165,
 0.00284,
 0.01951,
 0.02644,
 0.00611,
 0.01231,
 0.01695,
 0.02431,
 0.00515,
 0.01515,
 0.0106,
 0.008,
 0.008,
 0.00819,
 0.00819,
 0.00819,
 0.02401,
 0.02652,
 0.02221,
 0.02095,
 0.0209,
 0.0086,
 0.0086,
 0.01405,
 0.00908,
 0.02705,
 0.01165,
 0.02182,
 0.01737,
 0.02716,
 0.02548,
 0.00918,
 0.03242,
 0.01639,
 0.01771,
 0.00687,
 0.01231,
 0.03242,
 0.01797,
 0.0121,
 1.30794,
 0.01194,
 0.00746,
 0.00319,
 0.01843,
 0.03488,
 0.03185,
 0.0222,
 0.01708,
 0.01687,
 0.01982,
 0.02464,
 0.02239,
 0.02566,
 0.01694,
 0.00806,
 0.00402,
 0.01521,
 0.02248,
 0.01523,
 0.01553,
 0.00609]

In [137]:
target4.index
for i in (0,len(target.index)):
    val=round(distance.euclidean((float(longitude),float(latitude)), (x_list[i], y_list[i])),5)
    target4['거리'][i].append(val)

target4

KeyError: 0

In [120]:
for i in list_dis:
    list2.append(i)

target4["거리"]=pd.DataFrame(list2)
target4

,FACI_STAT,CP_NM,CPB_NM,FACI_POINT_X,FACI_POINT_Y,FACI_TEL,거리
298,정상운영,서울특별시,중구,126.991127,37.560088,02-2280-8000,0.01592
326,정상운영,서울특별시,중구,127.016534,37.564217,NaN,0.01515
327,정상운영,서울특별시,중구,126.973561,37.559473,NaN,0.01060
528,정상운영,서울특별시,중구,126.985168,37.562531,NaN,NaN
529,정상운영,서울특별시,중구,126.985168,37.562531,NaN,NaN
...,...,...,...,...,...,...,...
107583,정상운영,서울특별시,중구,126.985128,37.560416,NaN,NaN
107696,정상운영,서울특별시,중구,127.020981,37.566794,02-2231-5547,NaN
107712,정상운영,서울특별시,중구,127.015401,37.558988,02-2238-8347,NaN
108213,정상운영,서울특별시,중구,126.986150,37.564903,NaN,NaN
108274,정상운영,서울특별시,중구,126.994825,37.561141,NaN,NaN

In [122]:
target4.to_csv("거리.csv")